booking_app/urls.py
from django.urls import path
from booking_app import views

app_name = 'booking_app'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('building/<slug:building_name_slug>/',views.ShowBuildingView.as_view(), name='show_building'),
    path('building/<slug:building_name_slug>/<slug:room_name_slug>/',views.ShowRoomView.as_view(), name='show_room'),
    path('registration/', views.register, name='register'),
    path('register_profile/', views.RegisterProfileView.as_view(), name='register_profile'),
    path('profile/<username>/', views.ProfileView.as_view(), name='profile'),
    
    # Ajax Test
    path('test/', views.Test.as_view(), name='test'),
    path('like_building/', views.LikeBuildingView.as_view(), name='like_building'),
    
    # Fullcalendar test
    path('fullcalendar_test/', views.FullcalendarTest.as_view(), name='fullcalendar_test'),
]

booking_system/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from booking_app import views

# 2 imports for media
from django.conf import settings
from django.conf.urls.static import static

# 2 imports for registration
from registration.backends.simple.views import RegistrationView
from django.urls import reverse

# Overridden RegistrationView
class MyRegistrationView(RegistrationView):
    def get_success_url(self, user):
        return reverse('booking_app:register_profile')

# Urls
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('booking_system/', include('booking_app.urls')),
    path('admin/', admin.site.urls),
    
    # Reference to the registration package
    path('accounts/register/', MyRegistrationView.as_view(), name='registration_register'),
    path('accounts/', include('registration.backends.simple.urls')),
    
    # Final step for media (serve static content from MEDIA_URL)
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

booking_app/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User
# Create your models here.

class Building(models.Model):
    
    #Attributes
    name = models.CharField(max_length=128, unique=True)
    
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Building, self).save(*args, **kwargs)
    
    #class Meta:
        #verbose_name_plural = ''
    
    def __str__(self):
        return self.name
        
class Room(models.Model):
    # ForeignKey
    building = models.ForeignKey(Building, on_delete=models.CASCADE)
    
    # Attributes
    name = models.CharField(max_length=128)
    number = models.CharField(max_length=128)
    manager = models.CharField(max_length=128)
    
    # Webpage Attributes
    views = models.IntegerField(default=0)
    bookmarked = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Room, self).save(*args, **kwargs)
    
    def __str__(self):
        return self.name
        
class Date(models.Model):
    # ForeignKey
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    
    # Attributes
    datelabel = models.CharField(max_length=128)
    
    def __str__(self):
        return self.datelabel
        
class Timeperiod(models.Model):
    # ForeignKey
    date = models.ForeignKey(Date, on_delete=models.CASCADE)

    # Attributes
    timelabel = models.CharField(max_length=128)

    def __str__(self):
        return self.timelabel
        


class UserProfile(models.Model):
    # ForeignKey
    # Links UserProfile to a User model instance
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    
    # Additional attributes
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)
    
    # Additional attributes2
#    bookings =
    
    def __str__(self):
        return self.user.username

class Event(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=128)
    time = models.CharField(max_length=128)
    date = models.CharField(max_length=128)
    room = models.CharField(max_length=128)

    def __str__(self):
        return self.name

    
"""
Booking_app models.py
"""
# Test for Fullclanedar API
#class Events(models.Model):
#    even_id = models.AutoField(primary_key=True)
#    event_name = models.CharField(max_length=255,null=True,blank=True)
#    start_date = models.DateTimeField(null=True,blank=True)
#    end_date = models.DateTimeField(null=True,blank=True)
#    event_type = models.CharField(max_length=10,null=True,blank=True)
#
#    def __str__(self):
#        return self.event_name

booking_app/forms.py
from django import forms
from django.contrib.auth.models import User
from booking_app.models import UserProfile

# Two classes inheriting from forms.ModelForm.
class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password',)

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('website', 'picture',)

"""
booking_app form.py
"""

booking_app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.urls import reverse

# Import django-registration-redux
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

# Import models
from booking_app.models import Building, Room, UserProfile, Event

# Import forms
from booking_app.forms import UserForm, UserProfileForm

from datetime import datetime
from django.views import View
from django.utils.decorators import method_decorator

from django.contrib.auth.models import User

#from django.http import JsonResponse
#import json


# Views:
# Index page view
class IndexView(View):
    def get(self, request):
        building_list = Building.objects.order_by('-likes')[:5]
        
        context_dict = {}
        context_dict['buildings'] = building_list
        return render(request, 'booking_app/index.html', context=context_dict)
        
# Show buildings
class ShowBuildingView(View):
    def create_context_dict(self, building_name_slug):
        context_dict = {}

        try:
            building = Building.objects.get(slug=building_name_slug)
            rooms = Room.objects.filter(building=building).order_by('-views')

            context_dict['rooms'] = rooms
            context_dict['building'] = building

        except Building.DoesNotExist:
            context_dict['rooms'] = None
            context_dict['building'] = None

        return context_dict

    def get(self, request, building_name_slug):
        context_dict = self.create_context_dict(building_name_slug)
        return render(request, 'booking_app/building.html', context_dict)

class ShowRoomView(View):
    def create_context_dict(self, room_name_slug):
        context_dict = {}

        try:
            room = Room.objects.get(slug=room_name_slug)
            context_dict['room'] = room
            
        except Room.DoesNotExist:
            context_dict['room'] = None

        return context_dict

    def get(self, request, room_name_slug, building_name_slug):
        context_dict = self.create_context_dict(room_name_slug)
        return render(request, 'booking_app/room.html', context_dict)


# Register view

def register(request):
    registered = False
    
    if request.method == 'POST':
        user_form = UserForm(request.POST)
        profile_form = UserProfileForm(request.POST)
        
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            
            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']
        
            profile.save()
            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()
    return render(request,'booking_app/register.html',context = {'user_form': user_form,'profile_form': profile_form,'registered': registered})


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        
        user = authenticate(username=username, password=password)
        
        if user:
            if user.is_active:
                login(request, user)
                return redirect(reverse('booking_app:index'))
            else:
                return HttpResponse("Your account is disabled.")
        else:
            print(f"Invalid login details: {username}, {password}")
            return HttpResponse("Invalid login details supplied.")

# like building
class LikeBuildingView(View):
    @method_decorator(login_required)
    def get(self, request):
        building_id = request.GET['building_id']

        try:
            building = Building.objects.get(id=int(building_id))
        except Building.DoesNotExist:
            return HttpResponse(-1)
        except ValueError:
            return HttpResponse(-2)
        
        building.likes = building.likes + 1
        building.save()

        return HttpResponse(building.likes)


class AddEventView(View):
    @method_decorator(login_required)
    def get(self, request):
        title = request.GET['title']
        start = request.GET['start']
        end = request.GET['end']
        
        e = Event.objects.get_or_create(title=title,start=start,end=end)

        return HttpResponse(True)


# Register user profile
class RegisterProfileView(View):
    @method_decorator(login_required)
    def get(self, request):
        form = UserProfileForm()
        context_dict = {'form': form}
        return render(request, 'booking_app/profile_registration.html', context_dict)
    
    @method_decorator(login_required)
    def post(self, request):
        form = UserProfileForm(request.POST, request.FILES)

        if form.is_valid():
            user_profile = form.save(commit=False)
            user_profile.user = request.user
            user_profile.save()

            return redirect(reverse('booking_app:index'))
        else:
            print(form.errors)
        
        context_dict = {'form': form}
        return render(request, 'booking_app/profile_registration.html', context_dict)


class ProfileView(View):
    def get_user_details(self, username):
        try:
            user = User.objects.get(username=username)
        except User.DoesNotExist:
            return None
        
        user_profile = UserProfile.objects.get_or_create(user=user)[0]
        form = UserProfileForm({'website': user_profile.website,
                                'picture': user_profile.picture})
        
        return (user, user_profile, form)
    
    @method_decorator(login_required)
    def get(self, request, username):
        try:
            (user, user_profile, form) = self.get_user_details(username)
        except TypeError:
            return redirect(reverse('booking_app:index'))
        
        context_dict = {'user_profile': user_profile,
                        'selected_user': user,
                        'form': form}
        
        return render(request, 'booking_app/profile.html', context_dict)
    
    @method_decorator(login_required)
    def post(self, request, username):
        try:
            (user, user_profile, form) = self.get_user_details(username)
        except TypeError:
            return redirect(reverse('booking_app:index'))
        
        form = UserProfileForm(request.POST, request.FILES, instance=user_profile)

        if form.is_valid():
            form.save(commit=True)
            return redirect(reverse('booking_app:profile',
                                    kwargs={'username': username}))
        else:
            print(form.errors)
        
        context_dict = {'user_profile': user_profile,
                        'selected_user': user,
                        'form': form}
        
        return render(request, 'booking_app/profile.html', context_dict)

# Ajax tests
class Test(View):
    @method_decorator(login_required)
    def get(self, request):
    
        
        name = request.GET['name']
        time = request.GET['time']
        date = request.GET['date']
        room = request.GET['room']
        
        e = Event.objects.get_or_create(name=name,time=time,date=date,room=room)
        
        return HttpResponse(name)

# Fullcalendar test page
class FullcalendarTest(View):
    def get(self, request):
        context_dict = {}
        return render(request, 'booking_app/calendar_test.html', context=context_dict)

templates/booking_app/base.html
<!DOCTYPE html>

{% load staticfiles %}
{% load booking_app_template_tags %}

<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="icon" href="{% static 'images/favicon.ico' %}">
            
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        
        
        <!-- Fullcalendar API -->
        <link href='{% static 'fullcalendar/lib/main.css' %}' rel='stylesheet' />
        <link href='{% static 'css/styles.css' %}' rel='stylesheet' />
        

        <!-- Title -->
        <title>
            School Facility Booking System  - {% block title_block %}Welcome!{% endblock %}
        </title>
    </head>
    
    
    <body>
        <header>
            <!-- Navbar -->
            <nav class="navbar navbar-expand-lg navbar-dark fixed-top bg-dark p-0">
                <a class="navbar-brand p-2" href="{% url 'booking_app:index' %}">Booking System</a>
                <!-- Navbar buttons -->
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    
                    <span class="navbar-toggler-icon"></span>
                </button>
                
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item"><a class="nav-link" href="{% url 'booking_app:index' %}">Home</a></li>
                        
                        <!-- If User has signed in -->
                        {% if user.is_authenticated %}

                        <!-- Dropdown profile menu -->
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Profile
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{% url 'booking_app:profile' user.username %}">My profile</a>
                                <a class="dropdown-item" href="{% url 'auth_password_change' %}">Change Password</a>
                            </div>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'auth_logout' %}?next=/booking_system/">
                                Logout
                            </a>
                        </li>
                        
                        <!-- If User haven't signed in　-->
                        {% else %}
                        <li class="nav-item">
                        <!-- <a class="nav-link" href="{% url 'booking_app:register' %}" role="button">Register</a> -->
                            <a class="nav-link" href="{% url 'registration_register' %}" role="button">Register</a>
                        </li>
                        
                        <li class="nav-item"><a class="nav-link" href="{% url 'auth_login' %}">Login</a></li>
                        {% endif %}
                    </ul>
                </div>
            </nav>
            <!-- End of Nav bar -->
        </header>
        
        
        <hr class="my-4">
        <div class="container-fluid">
            <div class="row">
                
                <!-- Side bar -->
                <nav class="col-md-2 d-none d-md-block bg-light sidebar">
                    <hr class="my-3">
                    {% if user.is_authenticated %}
                    
                    <!-- Search bar -->
                    <div class="w-75 ml-3">
                        <input type="search" id="search-input" class="form-control ds-input" placeholder="Search..." />
                    </div>
                    
                    <!-- Cards -->
                    <hr class="my-3">
                    <div class="sidebar-sticky" id="categories-listing">
                        <div class="card mb-6">
                            <div class="card-body">
                                <h7>My bookings:</h3>
                                <p class="card-text">

                                </p>
                            </div>
                        </div>
                        
                    </div>
                    
                    <hr class="my-3">
                    
                    <div class="sidebar-sticky" id="categories-listing2">
                        <div class="card mb-6">
                            <div class="card-body">
                                <h7>Bookmarks:</h3>
                                <p class="card-text">

                                </p>
                            </div>
                        </div>
                        
                    </div>
                    
                    <!-- room list -->
                    
                    <div class="sidebar-sticky" id="room-listing">
                        {% get_room_list room %}
                    </div>
                    
                    <!-- User haven't logged in -->
                    {% else %}
                    <!-- Side bar login form -->
                    <h3>Please Login</h3>
                    
                    <div class="w-75 ml-3">
                        <form class="form-signin" role="form" method="post" action="/accounts/login/">
                            {% csrf_token %}
                            <p><input type="text" name="username" id="id_username" class="form-control" placeholder="Username" required autofocus></p>
                            <p><input type="password" name="password" id="id_password" class="form-control" placeholder="Password" required></p>
                            <p><button class="btn btn-md btn-primary btn-block" type="submit" value="Submit">
                                Sign in</button></p>
                        </form>
                    </div>
                    
                    <hr class="my-4">
                    <div class="w-75 ml-3">
                        <p class="lead">
                        <a class="btn btn-md btn-primary btn-block" href="{% url 'registration_register' %}" role="button">Register
                        </a>
                        </p>
                    </div>
                    {% endif %}
                </nav>
                
                <!-- Main content -->
                <main role="main" class="col-md-9  ml-sm-auto col-lg-10 px-4">
                    {% block body_block %}{% endblock %}
                </main>
            </div>
        </div>
        
        <!-- Optional JavaScript (calendar scriptes) -->
        <script src="{% static 'fullcalendar/lib/main.js' %}"></script>
        <script src="{% static 'js/fullcalendar-scripts.js' %}"></script>
        
        <!-- Bootstrap core JavaScript -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
        <script src="{% static 'js/layout-jquery.js' %}"></script>
        <script src="{% static 'js/ajax.js' %}"></script>
        <script>window.jQuery || document.write('<script src="https://getbootstrap.com/docs/4.2/assets/js/vendor/jquery-slim.min.js"><\/script>')</script><script src="https://getbootstrap.com/docs/4.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-zDnhMsjVZfS3hiP7oCBRmfjkQC4fzxVxFhBx8Hkz2aZX8gEvA/jsP3eXRCvzTofP" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
        <script src="https://getbootstrap.com/docs/4.2/examples/dashboard/dashboard.js"></script>
    </body>
</html>

templates/booking_app/building.html
{% extends 'booking_app/base.html' %}
{% load staticfiles %} <!-- New line -->

{% block title_block %}
    Building
{% endblock %}

{% block body_block %}

<!--Main content-->
<div class="jumbotron p-4">
    {% if building %}
    <h1>{{ building.name }}</h1>
    <div>
        <strong id="like_count">{{ building.likes }}</strong> likes
        {% if user.is_authenticated %}
        <button id="like_btn"
            data-buildingid="{{ building.id }}"
            class="btn btn-primary btn-sm"
            type="button">
            <span data-feather="thumbs-up"></span>
            Like
        </button>
        {% endif %}
    </div>
        
        
</div>

<div class="jumbotron p-4">
        <p class="lead">
        Hello, <strong>{{ user.username }}</strong>!<br/>
        Here is {{ building.name }}<br/>
        Please select the room you would like to book
        </p>
        <hr class="my-4">
        {% if rooms %}
        <ul>
            {% for room in rooms %}
            <li>
                <p>
                <a class="btn btn-outline-primary btn-md"
                    href="/booking_system/building/{{ building.slug }}/{{ room.slug }}/">
                    {{ room.name }}
                </a>
                </p>
            </li>
            {% endfor %}
        </ul>
        {% else %}
        <strong>No room currently available in this building.</strong>
        {% endif %}
        
        <hr class="my-4">
        <div class="jumbotron p-4">
            <a class="btn btn-info" href="{% url 'booking_app:index' %}" role="button">
                    Back to Homepage
            </a>
        </div>
    {% else %}
    The specified building does not exist.
    {% endif %}
</div>

{% endblock %}

templates/booking_app/calendar_test.html
{% extends 'booking_app/base.html' %}
{% load staticfiles %} <!-- New line -->

{% block title_block %}
    Room
{% endblock %}

{% block body_block %}

<!--Main content-->

<div class="jumbotron p-4">
    <h1>Fullcalendar demonstration Page</h1>
</div>

<!--Fullcalendar API-->
<div class="jumbotron p-4">
    <div id='calendar'></div>

    <hr class="my-4">
    <div class="jumbotron p-4">
        <a class="btn btn-info" href="{% url 'booking_app:index' %}" role="button">
                Back to Homepage
        </a>
    </div>
</div>


{% endblock %}

templates/booking_app/profile.html
{% extends 'booking_app/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Profile for {{ selected_user.username }}
{% endblock %}

{% block body_block %}
<div class="jumbotron p-4">
    <div class="container">
        <h1 class="jumbotron-heading">{{ selected_user.username }}'s Profile</h1>
    </div>
</div>

<div class="container">
    <div class="row">
        {% if user_profile.picture %}
        <img src="{{ MEDIA_URL }}{{ user_profile.picture }}"
        width="300"
        height="300"
        alt="{{ selected_user.username }}'s profile image" />
        {% else %}
        <img src="{% static 'images/default.png' %}" width="300" height="300" alt="Placeholder image" />
        {% endif %}
        <br />
        <div>
            {% if selected_user == user %}
            <form method="post" action="." enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}

                <input class="btn btn-primary" type="submit" value="Update" />
            </form>
        
            
            
            {% else %}
            <p>
                <strong>Website: </strong>
                <a href="{{ user_profile.website }}">{{ user_profile.website }}</a>
            </p>
            {% endif %}
            
            <hr class="my-4">
            <a class="btn btn-info" href="{% url 'booking_app:index' %}" role="button">
                    Back to Homepage
            </a>

        </div>
    </div>
</div>
{% endblock %}

templates/booking_app/profile_registration.html
{% extends 'booking_app/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Register - Step 2
{% endblock %}

{% block body_block %}
<div class="jumbotron p-4">
    <div class="container">
        <h1 class="jumbotron-heading">Register Here - Step 2</h1>
    </div>
</div>

<div class="container">
    <div class="row">
        <form method="post" action="{% url 'booking_app:register_profile' %}" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Create Profile" />
        </form>
    </div>
</div>
{% endblock %}

templates/booking_app/register.html
{% extends 'booking_app/base.html' %}
{% load staticfiles %} <!-- New line -->

{% block title_block %}
    Register
{% endblock %}

{% block body_block %}
<!--
                  
                  <li class="nav-item">
                    
                    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" data-whatever="@mdo">Login</button>
                    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                      <div class="modal-dialog">
                        <div class="modal-content">
                          <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Welcome!</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                              <span aria-hidden="true">&times;</span>
                            </button>
                          </div>
                          <div class="modal-body">
                            <form>
                              <div class="input-group mb-3">
                                <div class="input-group-prepend">
                                  <span class="input-group-text" id="basic-addon1">Username</span>
                                </div>
                                <input type="text" class="form-control" placeholder="Username" aria-label="Username" aria-describedby="basic-addon1">
                              </div>
                              
                              <div class="input-group mb-3">
                                <div class="input-group-prepend">
                                  <span class="input-group-text" id="basic-addon2"> Password </span>
                                </div>
                                <input type="text" class="form-control" placeholder="Password" aria-label="Password" aria-describedby="basic-addon2">
                              </div>

                            
                                  
                            </form>
                          </div>
                          <div class="modal-footer">
                            <button type="button" class="btn btn-primary">Login</button>
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            
                          </div>
                        </div>
                      </div>
                    </div>
                    
                  </li>
                  
                </ul>
                
-->

<div class="jumbotron p-4">
    <div class="container">
        <h1 class="jumbotron-heading">Register Here</h1>
    </div>
</div>

<div class="jumbotron">
    <div class="container">
        <div>
            {% if registered %}
            <strong>Thank you for registering!</strong>
            <hr class="my-4">
            <a class="btn btn-primary" href="{% url 'booking_app:index' %}" role="button">Return to homepage</a>
            <a class="btn btn-primary" href="{% url 'booking_app:profile' user.username %}" role="button">View my profile</a>
            
            
            {% else %}
             <!-- <strong>Please register here!</strong><br/> -->
            <form id="user_form" method="post" action="{% url 'booking_app:register' %}"
                  enctype="multipart/form-data">
                {% csrf_token %}
                {{ user_form.as_p }}
                {{ profile_form.as_p }}
                <!--
                {{ user_form.as_p }}
                {{ profile_form.as_p }}
                -->
                
                <!--
                <div class="form-group">
                    <p class="required">
                        <label class="required" for="id_username">Username:</label>
                        <input class="form-control" id="id_username" maxlength="30" name="username" type="text" />
                        <span class="helptext">
                            Required. 30 characters or fewer.
                            Letters, digits and @/./+/-/_ only.
                        </span>
                    </p>
                    <p class="required">
                        <label class="required" for="id_email">E-mail:</label>
                        <input class="form-control" id="id_email" name="email" type="email" />
                    </p>
                    <p class="required">
                        <label class="required" for="id_password1">Password:</label>
                        <input class="form-control" id="id_password1" name="password1" type="password" />
                    </p>
                    <p class="required">
                        <label class="required" for="id_password2">Password confirmation:</label>
                        <input class="form-control" id="id_password2" name="password2" type="password" />
                        <span class="helptext">
                            Enter the same password as before, for verification.
                        </span>
                    </p>
                </div>
                
                
                <button type="submit" class="btn btn-primary">Submit</button>
                -->
                <input class="btn btn-primary" type="submit" name="submit" value="Register" />
                
                
            </form>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}
        